#This file is for instructions only. Make any changes to config.yml.
general:
  debug: false
  #will check for a newer version and alert any OP when they login to the server
  checkforupdate: true
  #Set to true to only allow VR players to play.
  vive-only: false
  #If true, creates an exclusion for vive-only for opped players. No effect if vive-only is false.
  allow-op: true
  #The message to show kicked non-vive players.
  vive-only-kickmessage: This server is configured for Vivecraft VR players only.
  #Ticks to wait before kicking a player. The player's client must send a Vivecraft VERSION info in that time.
  vive-only-kickwaittime: 200
  #Set to false to disable registering Vivecraft-specific crafting recipes.
  vive-crafting: true
SendPlayerData:
  #Send player data to all clients with Vivecraft
  enabled: true
CreeperRadius:
  #Distance from a Vivecraft player before creeper starts to swell up (vanilla is 3)
  enabled: true
  radius: 1.75
setSpigotConfig:
  enabled: true
  #Increase these if you get rubber banding when teleporting.
  movedWronglyThreshold: 15
  movedTooQuickly: 64
pvp:
  #Allows Standing VR players to Attack other Standing VR Players
  VRvsVR: true 
  #Allows Standing VR Players to attack Non VR players
  VRvsNONVR: true
  #Allows  Seated VR Players to attack normal players.
  SEATEDVRvsNONVR: true
  #Allows Standing VR Players to attack Seated VR Players
  VRvsSEATEDVR: true
bow:
  #Archery damage multiplier for Vivecraft (standing) users. Set to 1 to disable
  standingmultiplier: 2
  #Archery damage multiplier for Vivecraft (seated) users. Set to 1 to disable
  seatedmultiplier: 1
  #Headshot damage multiplier for Vivecraft (standing) users. Set to 1 to disable
  standingheadshotmultiplier: 3
  #Headshot damage multiplier for Vivecraft (seated) users. Set to 1 to disable
  seatedheadshotmultiplier: 2
  #Set if players can headshot mobs (only horizontal mobs)
  headshotmobs: true
permissions:
  #enable setting player groups for vive users.
  enabled: false
  #Permission group for Vive users
  vivegroup: vive.vivegroup
  #Permission group for non-Vive users
  non-vivegroup: vive.non-vivegroup
  #Permission group for vive users in free move mode.
  freemovegroup: vive.freemovegroup
  #Permission to override climb limitations.
  climbperm: vive.climbanywhere
welcomemsg:
  enabled: false
  #Remove message to not send or set to nothing. ex: leaveMessage:
  welcomeVR: '&player has joined with standing VR!'
  welcomenonVR: '&player has joined with Non-VR companion!'
  welcomeSeated: '&player has joined with seated VR!' 
  welcomeVanilla: '&player has joined as a Muggle!' 
  leaveMessage: '&player has disconnected from the server!'
climbey:
  #Allows use of jump_boots and climb_claws. Provide with /give (player) climb_claws | jump_boots
  enabled: false
  #Sets which blocks are climb-able. Options are 'None': List ignored. All blocks are climbable. 'Include': Only blocks on the list are climbable. 'Exclude': All blocks are climbable except those on the list
  blockmode: None
  #The list of block names for use with include/exclude block mode.
  blocklist:
    - white_wool
    - dirt
    - grass_block
crawling:
  #Allows use of roomscale crawling. Disabling does not prevent vanilla crawling.
  enabled: false
teleport:
  #Whether direct teleport is enabled. It is recommended to leave this enabled for players prone to VR sickness.
  enable: true
  #Limit teleport range and frequency in survival
  limitedsurvival: false
  #Maximum blocks players can teleport up. Set to 0 to disable. Max: 4
  uplimit: 1
  #Maximum blocks players can teleport down. Set to 0 to disable. Max: 16
  downlimit: 4
  #Maximum blocks players can teleport horizontally. Set to 0 to disable. Max: 32
  horizontallimit: 16
worldscale:
  #Limit the range of world scale players can use
  limitrange: false
  #Upper limit of range
  max: 2
  #Lower limit of range
  min: 0.5
settingOverrides:
  #Forces players to use the raw item position setting
  thirdPersonItems: false